server:
  port: 8081
  servlet:
    context-path: /store

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookstore"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 100
  refreshable-duration: 10000